services:
  minecraft-rad3:
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons-3"
      CF_API_KEY: ${CF_API_KEY}
      MEMORY: ${MC_MEMORY:-6144M}
      MOTD: ${MC_MOTD:-Roguelike Adventures}
      ONLINE_MODE: "false"
      ENFORCE_WHITELIST: ${MC_ENFORCE_WHITELIST:-false}
      WHITELIST: ${MC_WHITELIST:-}
      OPS: ${MC_OPS:-}
      USE_MEOWICE_FLAGS: "true"
      TZ: ${TZ:-America/Havana}
      MANAGEMENT_SERVER_ENABLED: "false"
    ports:
      - "${MC_PORT:-25565}:25565/tcp"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    x-runtipi:
      is_main: true
      internal_port: 25565

x-runtipi:
  schema_version: 2
  overrides: []
